name: Configscanner Action

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:

  workflow_dispatch:
    inputs:
      owner:
        description: Provide the owner of the Application
        required: true
      
      repo:
        description: Provide the name of the Repository
        required: true
      
jobs:
  annotate-pr:
    runs-on: windows-latest
    name: Reads all the files with hardcoded values
   
    steps:
      - uses: ./
      - name : execute my action
        run : |