name: Configscanner Action

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
jobs:
  annotate-pr:
    runs-on: windows-latest
    name: Reads all the files with hardcoded values
   
    steps:
      - uses: actions/checkout@v2
      - uses: ./
      - name : execute my action
        run : |