name: Configscanner Action

on: 
  pull_request:
    types: [opened, reopened, synchronize]
  push:
jobs:
  annotate-pr:
    runs-on: windows-latest
    name: Reads all the files with hardcoded values
   
    steps:
      - name: repo and owner name
        run: echo  ${{ github.repository_owner }}
             echo ${{ github.event.repository.name }}
      - name: Execute to read the pages
        uses: link-/myconfigscanner@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}